### ISSUE TITLE
Missing GameVariantCategory VIP (23)

### ISSUE THREAD

**Issue by davidhouweling** [GravlLift/halo-infinite-api#4]
Just doing some poking around and noticed that `GameVariantCategory` is missing `VIP` which is number `23`.

Here is game data for a VIP match: [vip.json](https://github.com/user-attachments/files/18139548/vip.json)

Perhaps if there is any additional data we wanted to point out such as `VipStats`? to make it available in the `MatchStats`?

**Comment by GravlLift** [comment]
Yeah, I've been adding those as needed, and VIP hadn't crossed my use case next. Thanks for the JSON sample, made adding this much simpler. :)

Added in version `9.1.1`.
